In [1]:
import numpy as np
import pandas as pd
import scipy as sp
import scipy.stats as stats
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

import os
import glob
import sys

In [2]:
from utils import set_basepath

In [3]:
sys.path[0]

'/Users/jacobhow/Documents/programming-projects/nfl-big-data/notebooks/feature'

In [4]:
basepath = set_basepath(steps=2)

In [5]:
sys.path[0]

'/Users/jacobhow/Documents/programming-projects/nfl-big-data'

In [6]:
from src.team import Team
from src.game import Game
from src.play import Play
from src.player import Player
from src.analysis import Analysis, sort_plays_by_result

In [7]:
analysis = Analysis(basepath=basepath)

In [8]:
analysis.load_data()

In [10]:
analysis.load_offensive_production()

In [12]:
op = analysis.offensive_production

In [13]:
snap_threshold = 100

In [15]:
op = op[op['snaps'] > snap_threshold]

In [16]:
op

,displayName,position,snaps,targets,epa,games played,team,target %,epa/snap,epa/target,epa/game
2558149,JuJu Smith-Schuster,WR,691,171,56.760971,16,PIT,24.7,0.082,0.332,3.548
2540158,Zach Ertz,TE,629,155,32.106814,16,PHI,24.6,0.051,0.207,2.007
2543468,Mike Evans,WR,610,144,57.318898,16,TB,23.6,0.094,0.398,3.582
2555295,Sterling Shepard,WR,610,81,23.387216,16,NYG,13.3,0.038,0.289,1.462
2552600,Nelson Agholor,WR,604,98,19.955120,16,PHI,16.2,0.033,0.204,1.247
...,...,...,...,...,...,...,...,...,...,...,...
2556460,Geronimo Allison,WR,169,31,16.627398,5,GB,18.3,0.098,0.536,3.325
2507166,Ted Ginn,WR,146,30,-2.296284,5,NO,20.5,-0.016,-0.077,-0.459
2543683,Austin Seferian-Jenkins,TE,126,18,1.354293,5,JAX,14.3,0.011,0.075,0.271
2561054,Damion Ratley,WR,119,20,-1.744443,5,CLE,16.8,-0.015,-0.087,-0.349
2540148,Tyler Eifert,TE,102,21,11.655220,4,CIN,20.6,0.114,0.555,2.914

In [20]:
op = op[op['epa/snap'] > 0]

In [21]:
op.sort_values('epa/snap',ascending=False)

,displayName,position,snaps,targets,epa,games played,team,target %,epa/snap,epa/target,epa/game
2552430,Tyler Lockett,WR,414,69,75.703617,15,SEA,16.7,0.183,1.097,5.047
2555346,Will Fuller,WR,216,49,39.066550,7,HOU,22.7,0.181,0.797,5.581
2556370,Michael Thomas,WR,532,158,94.735736,16,NO,29.7,0.178,0.600,5.921
2560957,Mark Andrews,TE,279,54,41.004434,16,BAL,19.4,0.147,0.759,2.563
2532865,T.Y. Hilton,WR,507,130,71.025607,14,IND,25.6,0.140,0.546,5.073
...,...,...,...,...,...,...,...,...,...,...,...
2552478,Blake Bell,TE,114,11,0.484143,10,JAX,9.6,0.004,0.044,0.048
2532899,Doug Martin,RB,159,23,0.540240,16,OAK,14.5,0.003,0.023,0.034
2555331,Cody Core,WR,189,29,0.513280,14,CIN,15.3,0.003,0.018,0.037
2556462,Robby Anderson,WR,423,94,1.289639,14,NYJ,22.2,0.003,0.014,0.092
2555230,Kenyan Drake,RB,345,72,1.006057,16,MIA,20.9,0.003,0.014,0.063

In [23]:
op.loc[2552430]['epa/snap']

0.183