In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import os
import glob

In [2]:
basepath = os.path.expanduser('~/Documents/programming-projects/nfl-big-data/calculated-data')

In [43]:
output_basepath = os.path.expanduser('~/Documents/programming-projects/nfl-big-data/submission/tables')

In [3]:
glob.glob(os.path.join(basepath,'*.csv'))

['/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/man play results.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/player max speed + accel.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/man coverage production reduction.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/offensive production.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/player season coverages.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/team target coverage epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/team personal epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/non targeted man coverage epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/coverage scheme epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/targeted defensive player epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/zone coverage production reduction.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/zone play results.csv']

## Player Level

In [4]:
player_season_coverages = pd.read_csv(os.path.join(basepath,'player season coverages.csv'),index_col=0)

In [5]:
man_production_reduction = pd.read_csv(os.path.join(basepath,'man coverage production reduction.csv'),index_col=0).set_index('id')

In [6]:
zone_production_reduction = pd.read_csv(os.path.join(basepath,'zone coverage production reduction.csv'),index_col=0).set_index('id')

In [7]:
player_season_coverages.head()

,displayName,position,snaps,zone,zone-deep,zone-over,man,man-over,blitz,games played,Team,zone %,zone-deep %,zone-over %,man %,man-over %,blitz %,zone-total,man-total
306,Dominique Rodgers-Cromartie,CB,64,7,17,25,3,12,0,5,OAK,10.9,26.6,39.1,4.7,18.8,0.0,49,15
1302,Aqib Talib,CB,202,19,79,60,25,19,0,8,LA,9.4,39.1,29.7,12.4,9.4,0.0,158,44
2307,Orlando Scandrick,CB,462,43,89,84,146,100,0,13,KC,9.3,19.3,18.2,31.6,21.6,0.0,216,246
2354,Wesley Woodyard,ILB,381,54,12,250,0,5,60,14,TEN,14.2,3.1,65.6,0.0,1.3,15.7,316,5
4365,Brandon Carr,CB,517,69,91,98,154,94,11,16,BAL,13.3,17.6,19.0,29.8,18.2,2.1,258,248

In [8]:
man_production_reduction.head()

,name,man targeted coverage count,total man delta epa,mean man delta epa,safety help percent
id,,,,,
2533062,Stephon Gilmore,66,-26.421065,-0.400319,22.7
2558067,Marlon Humphrey,45,-22.161204,-0.492471,46.7
2559164,Michael Davis,41,-18.144583,-0.442551,19.5
89756,Jason McCourty,55,-16.882621,-0.306957,45.5
2543681,Kyle Fuller,56,-16.636283,-0.297076,41.1

In [9]:
zone_production_reduction.head()

,name,zone targeted coverage count,total zone delta epa,mean zone delta epa
id,,,,
2557927,Desmond King,29,-30.241365,-1.042806
2543681,Kyle Fuller,31,-27.847193,-0.898297
2555175,James Bradberry,53,-27.406165,-0.517097
2495872,Johnathan Joseph,43,-24.369903,-0.566742
2543470,Ha Ha Clinton-Dix,31,-22.503220,-0.725910

### Performance Analysis

In [19]:
df = pd.merge(player_season_coverages[['displayName','position','snaps','man-total','zone-total']],
              man_production_reduction.drop(columns=['name','safety help percent']),
              left_index=True,right_index=True)

In [20]:
df = pd.merge(df,zone_production_reduction.drop(columns=['name']),
              left_index=True,right_index=True)

In [21]:
df

,displayName,position,snaps,man-total,zone-total,man targeted coverage count,total man delta epa,mean man delta epa,zone targeted coverage count,total zone delta epa,mean zone delta epa
306,Dominique Rodgers-Cromartie,CB,64,15,49,2,0.442579,0.221290,5,-5.355782,-1.071156
1302,Aqib Talib,CB,202,44,158,10,-1.184709,-0.118471,10,-5.577872,-0.557787
2307,Orlando Scandrick,CB,462,246,216,60,8.473536,0.141226,23,-5.752900,-0.250126
4365,Brandon Carr,CB,517,248,258,54,-3.716949,-0.068832,20,-5.128446,-0.256422
71251,Patrick Chung,SS,525,168,313,35,1.050480,0.030014,35,-11.977567,-0.342216
...,...,...,...,...,...,...,...,...,...,...,...
2561316,Jalen Davis,CB,23,12,10,5,6.300327,1.260065,2,-1.117703,-0.558852
2561318,Tae Davis,ILB,190,5,151,2,2.831041,1.415520,7,-4.121987,-0.588855
2561340,Tre Herndon,CB,38,25,12,5,1.205910,0.241182,2,0.305361,0.152680
2561417,Charvarius Ward,CB,67,34,33,10,0.674194,0.067419,2,3.988404,1.994202
2561527,Mike Ford,CB,198,83,115,15,11.249367,0.749958,12,10.071364,0.839280

In [22]:
snap_threshold = 200

In [23]:
df = df[df['snaps'] > snap_threshold]
df

,displayName,position,snaps,man-total,zone-total,man targeted coverage count,total man delta epa,mean man delta epa,zone targeted coverage count,total zone delta epa,mean zone delta epa
1302,Aqib Talib,CB,202,44,158,10,-1.184709,-0.118471,10,-5.577872,-0.557787
2307,Orlando Scandrick,CB,462,246,216,60,8.473536,0.141226,23,-5.752900,-0.250126
4365,Brandon Carr,CB,517,248,258,54,-3.716949,-0.068832,20,-5.128446,-0.256422
71251,Patrick Chung,SS,525,168,313,35,1.050480,0.030014,35,-11.977567,-0.342216
71423,Brian Orakpo,OLB,303,3,96,1,-0.343774,-0.343774,2,-2.589056,-1.294528
...,...,...,...,...,...,...,...,...,...,...,...
2560966,Jerome Baker,LB,343,34,270,3,1.639706,0.546569,13,-1.285941,-0.098919
2561001,Grant Haley,CB,245,124,110,25,11.187032,0.447481,12,-1.041468,-0.086789
2561015,Lorenzo Carter,OLB,277,12,73,2,-2.469402,-1.234701,2,-1.358969,-0.679485
2561039,Carlton Davis,CB,362,219,143,43,-7.638645,-0.177643,13,7.892960,0.607151
2561132,Foye Oluokun,LB,262,35,210,2,1.453587,0.726794,8,1.255500,0.156938

In [24]:
df.keys()

Index(['displayName', 'position', 'snaps', 'man-total', 'zone-total',
       'man targeted coverage count', 'total man delta epa',
       'mean man delta epa', 'zone targeted coverage count',
       'total zone delta epa', 'mean zone delta epa'],
      dtype='object')

In [25]:
df['total targets'] = df['man targeted coverage count'] + df['zone targeted coverage count']
df['total delta epa'] = df['total man delta epa'] + df['total zone delta epa']
df['mean total delta epa'] = df['total delta epa'] / df['total targets']

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [26]:
df['target %'] = ((df['total targets'] / df['snaps']) * 100).round(1)
df['man target %'] = ((df['man targeted coverage count'] / df['man-total']) * 100).round(1)
df['zone target %'] = ((df['zone targeted coverage count'] / df['zone-total']) * 100).round(1)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [27]:
df

,displayName,position,snaps,man-total,zone-total,man targeted coverage count,total man delta epa,mean man delta epa,zone targeted coverage count,total zone delta epa,mean zone delta epa,total targets,total delta epa,mean total delta epa,target %,man target %,zone target %
1302,Aqib Talib,CB,202,44,158,10,-1.184709,-0.118471,10,-5.577872,-0.557787,20,-6.762581,-0.338129,9.9,22.7,6.3
2307,Orlando Scandrick,CB,462,246,216,60,8.473536,0.141226,23,-5.752900,-0.250126,83,2.720636,0.032779,18.0,24.4,10.6
4365,Brandon Carr,CB,517,248,258,54,-3.716949,-0.068832,20,-5.128446,-0.256422,74,-8.845395,-0.119532,14.3,21.8,7.8
71251,Patrick Chung,SS,525,168,313,35,1.050480,0.030014,35,-11.977567,-0.342216,70,-10.927087,-0.156101,13.3,20.8,11.2
71423,Brian Orakpo,OLB,303,3,96,1,-0.343774,-0.343774,2,-2.589056,-1.294528,3,-2.932830,-0.977610,1.0,33.3,2.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2560966,Jerome Baker,LB,343,34,270,3,1.639706,0.546569,13,-1.285941,-0.098919,16,0.353765,0.022110,4.7,8.8,4.8
2561001,Grant Haley,CB,245,124,110,25,11.187032,0.447481,12,-1.041468,-0.086789,37,10.145564,0.274204,15.1,20.2,10.9
2561015,Lorenzo Carter,OLB,277,12,73,2,-2.469402,-1.234701,2,-1.358969,-0.679485,4,-3.828371,-0.957093,1.4,16.7,2.7
2561039,Carlton Davis,CB,362,219,143,43,-7.638645,-0.177643,13,7.892960,0.607151,56,0.254315,0.004541,15.5,19.6,9.1
2561132,Foye Oluokun,LB,262,35,210,2,1.453587,0.726794,8,1.255500,0.156938,10,2.709087,0.270909,3.8,5.7,3.8

### Limit Analysis to CB's

In [28]:
cb_df = df[df['position'] == 'CB']

In [29]:
def score(df, key, score_name, negative=True):
    mu = df[key].mean()
    s = df[key].std()
    
    if negative:
        df[score_name] = ((-(df[key] - mu) / s) * 10 + 50).round(1)
    else:
        df[score_name] = (((df[key] - mu) / s) * 10 + 50).round(1)

In [30]:
score(cb_df, 'mean total delta epa', 'Total Coverage Score')
score(cb_df, 'mean man delta epa', 'Man Coverage Score')
score(cb_df, 'mean zone delta epa', 'Zone Coverage Score')

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [31]:
score(cb_df, 'target %', 'Target % Score')
score(cb_df, 'man target %', 'Man Target % Score')
score(cb_df, 'zone target %', 'Zone Target % Score')

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [33]:
sort_key = 'Total Coverage Score'
cb_df.sort_values(sort_key, ascending=False).head(10)

,displayName,position,snaps,man-total,zone-total,man targeted coverage count,total man delta epa,mean man delta epa,zone targeted coverage count,total zone delta epa,...,mean total delta epa,target %,man target %,zone target %,Total Coverage Score,Man Coverage Score,Zone Coverage Score,Target % Score,Man Target % Score,Zone Target % Score
2557927,Desmond King,CB,432,122,298,23,-5.728416,-0.249062,29,-30.241365,...,-0.691727,12.0,18.9,9.7,73.8,57.1,70.7,55.1,53.8,47.2
2558067,Marlon Humphrey,CB,437,239,197,45,-22.161204,-0.492471,17,-14.716760,...,-0.594806,14.2,18.8,8.6,70.2,65.2,67.1,48.1,54.0,51.5
2555552,Ryan Smith,CB,247,83,164,19,0.349256,0.018382,15,-18.069314,...,-0.521178,13.8,22.9,9.1,67.5,48.2,74.0,49.4,45.0,49.6
2555177,Mackensie Alexander,CB,295,115,172,27,-13.536454,-0.501350,18,-9.777895,...,-0.518097,15.3,23.5,10.5,67.4,65.5,60.5,44.6,43.7,44.1
2555539,Xavien Howard,CB,404,155,249,34,-16.521947,-0.485940,13,-7.774421,...,-0.516944,11.6,21.9,5.2,67.4,65.0,61.6,56.3,47.2,64.8
2543681,Kyle Fuller,CB,593,246,346,56,-16.636283,-0.297076,31,-27.847193,...,-0.511304,14.7,22.8,9.0,67.2,58.7,67.7,46.5,45.2,50.0
2495872,Johnathan Joseph,CB,445,71,374,18,-5.785343,-0.321408,43,-24.369903,...,-0.494348,13.7,25.4,11.5,66.5,59.5,60.9,49.7,39.5,40.2
2543811,Pierre Desir,CB,485,234,251,35,-6.690312,-0.191152,17,-18.087348,...,-0.476493,10.7,15.0,6.8,65.9,55.2,71.1,59.2,62.3,58.6
2555175,James Bradberry,CB,538,136,401,36,-12.968532,-0.360237,53,-27.406165,...,-0.453648,16.5,26.5,13.2,65.0,60.8,59.9,40.8,37.1,33.5
2557867,Tre'Davious White,CB,487,253,233,46,-15.854256,-0.344658,10,-7.930646,...,-0.424730,11.5,18.2,4.3,64.0,60.3,65.6,56.6,55.3,68.4

In [38]:
display_keys = ['displayName','position','snaps','Total Coverage Score','Man Coverage Score','Zone Coverage Score',
                'Target % Score','Man Target % Score','Zone Target % Score']
display_cb_df = cb_df[display_keys].sort_values('Total Coverage Score',ascending=False)

In [42]:
display_cb_df_top15 = display_cb_df.head(15)
display_cb_df_top15

,displayName,position,snaps,Total Coverage Score,Man Coverage Score,Zone Coverage Score,Target % Score,Man Target % Score,Zone Target % Score
2557927,Desmond King,CB,432,73.8,57.1,70.7,55.1,53.8,47.2
2558067,Marlon Humphrey,CB,437,70.2,65.2,67.1,48.1,54.0,51.5
2555552,Ryan Smith,CB,247,67.5,48.2,74.0,49.4,45.0,49.6
2555177,Mackensie Alexander,CB,295,67.4,65.5,60.5,44.6,43.7,44.1
2555539,Xavien Howard,CB,404,67.4,65.0,61.6,56.3,47.2,64.8
2543681,Kyle Fuller,CB,593,67.2,58.7,67.7,46.5,45.2,50.0
2495872,Johnathan Joseph,CB,445,66.5,59.5,60.9,49.7,39.5,40.2
2543811,Pierre Desir,CB,485,65.9,55.2,71.1,59.2,62.3,58.6
2555175,James Bradberry,CB,538,65.0,60.8,59.9,40.8,37.1,33.5
2557867,Tre'Davious White,CB,487,64.0,60.3,65.6,56.6,55.3,68.4
2540197,Nickell Robey-Coleman,CB,340,63.1,63.6,56.9,57.6,52.9,51.5
2539237,D.J. Hayden,CB,257,62.0,67.3,47.7,54.7,43.2,61.7
2533062,Stephon Gilmore,CB,588,61.7,62.1,54.4,45.6,54.7,48.0
2506789,Tramon Williams,CB,540,61.6,61.0,56.5,72.5,54.9,70.3
1302,Aqib Talib,CB,202,60.8,52.8,60.8,61.7,45.4,60.5

In [44]:
display_cb_df_top15.to_csv(os.path.join(output_basepath,'CB Performance Evaluation.csv'))