In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import os
import glob

In [2]:
basepath = os.path.expanduser('~/Documents/programming-projects/nfl-big-data/calculated-data')

In [3]:
glob.glob(os.path.join(basepath,'*.csv'))

['/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/man play results.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/player max speed + accel.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/man coverage production reduction.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/offensive production.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/player season coverages.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/team target coverage epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/team personal epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/non targeted man coverage epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/coverage scheme epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/targeted defensive player epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/zone coverage production reduction.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/zone play results.csv']

## Team Level

In [4]:
team_personal_epa = pd.read_csv(os.path.join(basepath,'team personal epa analysis.csv'))

In [5]:
team_scheme_epa = pd.read_csv(os.path.join(basepath,'coverage scheme epa analysis.csv'))

In [6]:
target_coverage_epa = pd.read_csv(os.path.join(basepath,'team target coverage epa analysis.csv'))

In [7]:
team_scheme_epa.head()

,team,play count,cover 0 count,cover 1 count,cover 2 count,cover 3 count,cover 4 count,cover 6 count,cover 0 percent,cover 1 percent,...,cover 3 epa,cover 4 epa,cover 6 epa,overall epa rate,cover 0 epa rate,cover 1 epa rate,cover 2 epa rate,cover 3 epa rate,cover 4 epa rate,cover 6 epa rate
0,CHI,621,25,203,147,61,95,90,4.0,32.7,...,-4.563688,-42.775964,2.178439,-0.039385,0.102864,0.238308,-0.170072,-0.037716,-0.353520,0.018004
1,BUF,507,36,191,101,49,77,53,7.1,37.7,...,0.692472,-3.749987,-10.104115,-0.000929,-0.019888,-0.078861,0.203632,0.005723,-0.030992,-0.083505
2,BAL,596,78,236,94,67,60,57,13.1,39.6,...,-4.107474,14.625985,-15.831695,0.017707,0.077028,-0.146907,0.211167,-0.033946,0.120876,-0.130840
3,MIN,456,23,144,86,49,99,55,5.0,31.6,...,-4.847184,-15.370724,23.046011,0.040269,-0.051042,0.218759,-0.039331,-0.040059,-0.127031,0.190463
4,NE,613,93,305,96,37,55,27,15.2,49.8,...,4.465144,19.412516,5.699166,0.032357,-0.046609,-0.229732,0.195827,0.036902,0.160434,0.047101

In [8]:
team_personal_epa.head()

,team,play count,heavy count,standard count,nickel count,dime count,quarter count,heavy percent,standard percent,nickel percent,...,standard epa,nickel epa,dime epa,quarter epa,overall epa rate,heavy epa rate,standard epa rate,nickel epa rate,dime epa rate,quarter epa rate
0,CHI,621,3,78,496,42,2,0.5,12.6,79.9,...,7.599955,-25.658569,-11.040015,0.931636,-0.039385,0.030652,0.062810,-0.212054,-0.091240,0.007699
1,BUF,507,0,65,440,0,0,0.0,12.8,86.8,...,-5.723763,5.249235,0.000000,0.000000,-0.000929,0.000000,-0.047304,0.043382,0.000000,0.000000
2,BAL,596,1,56,308,226,5,0.2,9.4,51.7,...,15.185915,8.890013,-10.222289,-4.861716,0.017707,0.012903,0.125503,0.073471,-0.084482,-0.040179
3,MIN,456,2,49,398,6,0,0.4,10.7,87.3,...,10.348018,10.744882,1.064906,0.000000,0.040269,-0.031420,0.085521,0.088801,0.008801,0.000000
4,NE,613,10,51,297,182,73,1.6,8.3,48.5,...,19.217143,28.082868,-22.970695,-10.730886,0.032357,0.051540,0.158819,0.232090,-0.189840,-0.088685

In [9]:
target_coverage_epa.head()

,team,play count,man count,zone count,man+zone count,checkdown count,no coverage count,man percent,zone percent,man+zone percent,...,zone epa,man+zone epa,checkdown epa,no coverage epa,overall epa rate,man epa rate,zone epa rate,man+zone epa rate,checkdown epa rate,no coverage epa rate
0,CHI,595,153,201,26,65,150,25.7,33.8,4.4,...,-10.418636,-3.281712,-14.807724,-2.621828,-0.010730,0.161737,-0.051834,-0.126220,-0.227811,-0.017479
1,BUF,486,108,155,23,77,123,22.2,31.9,4.7,...,-0.124513,15.822149,-6.914055,9.499362,0.019237,-0.082722,-0.000803,0.687920,-0.089793,0.077231
2,MIN,436,122,149,17,84,64,28.0,34.2,3.9,...,9.484143,-1.280299,2.744966,10.321282,0.074216,0.090887,0.063652,-0.075312,0.032678,0.161270
3,NE,589,163,177,45,69,135,27.7,30.1,7.6,...,35.574739,-15.227899,-9.772139,38.720231,0.056979,-0.096530,0.200987,-0.338398,-0.141625,0.286817
4,BAL,539,156,164,23,82,114,28.9,30.4,4.3,...,18.049344,10.472397,-6.140205,26.131998,0.062272,-0.095827,0.110057,0.455322,-0.074881,0.229228

## Player Level

In [10]:
player_season_coverages = pd.read_csv(os.path.join(basepath,'player season coverages.csv'),index_col=0)

In [11]:
defensive_target_coverage_epa = pd.read_csv(os.path.join(basepath,'targeted defensive player epa analysis.csv'),index_col=0)

In [12]:
man_production_reduction = pd.read_csv(os.path.join(basepath,'man coverage production reduction.csv'),index_col=0)

In [13]:
zone_production_reduction = pd.read_csv(os.path.join(basepath,'zone coverage production reduction.csv'),index_col=0)

In [14]:
man_non_targeted_epa_analysis = pd.read_csv(os.path.join(basepath,'non targeted man coverage epa analysis.csv'),index_col=0)

In [15]:
player_season_coverages.head()

,displayName,position,snaps,zone,zone-deep,zone-over,man,man-over,blitz,games played,Team,zone %,zone-deep %,zone-over %,man %,man-over %,blitz %,zone-total,man-total
306,Dominique Rodgers-Cromartie,CB,64,7,17,25,3,12,0,5,OAK,10.9,26.6,39.1,4.7,18.8,0.0,49,15
1302,Aqib Talib,CB,202,19,79,60,25,19,0,8,LA,9.4,39.1,29.7,12.4,9.4,0.0,158,44
2307,Orlando Scandrick,CB,462,43,89,84,146,100,0,13,KC,9.3,19.3,18.2,31.6,21.6,0.0,216,246
2354,Wesley Woodyard,ILB,381,54,12,250,0,5,60,14,TEN,14.2,3.1,65.6,0.0,1.3,15.7,316,5
4365,Brandon Carr,CB,517,69,91,98,154,94,11,16,BAL,13.3,17.6,19.0,29.8,18.2,2.1,258,248

In [16]:
man_production_reduction = man_production_reduction.set_index('id')
man_production_reduction.head()

,name,man targeted coverage count,total man delta epa,mean man delta epa
id,,,,
2533062,Stephon Gilmore,66,-26.421065,-0.400319
2558067,Marlon Humphrey,45,-22.161204,-0.492471
2559164,Michael Davis,41,-18.144583,-0.442551
89756,Jason McCourty,55,-16.882621,-0.306957
2543681,Kyle Fuller,56,-16.636283,-0.297076

In [17]:
zone_production_reduction = zone_production_reduction.set_index('id')
zone_production_reduction.head()

,name,zone targeted coverage count,total zone delta epa,mean zone delta epa
id,,,,
2557927,Desmond King,29,-30.241365,-1.042806
2543681,Kyle Fuller,31,-27.847193,-0.898297
2555175,James Bradberry,53,-27.406165,-0.517097
2495872,Johnathan Joseph,43,-24.369903,-0.566742
2543470,Ha Ha Clinton-Dix,31,-22.503220,-0.725910

In [18]:
defensive_target_coverage_epa.head()

,targets,zone targets,zone targets epa,man targets,man targets epa,zone-over targets,zone-over targets epa,man-over targets,man-over targets epa
2555383,47,17.0,11.922586,22.0,0.542329,8.0,8.794294,NaN,NaN
79848,70,41.0,0.419929,11.0,10.043456,14.0,3.426184,4.0,-0.983954
2558175,4,3.0,-6.467198,NaN,NaN,NaN,NaN,1.0,-0.069654
2552689,65,26.0,2.585327,31.0,0.079026,8.0,-6.214528,NaN,NaN
2534832,5,5.0,-0.900719,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
man_non_targeted_epa_analysis.head()

,non targets,non targets epa,non targets - iso,non targets epa - iso,non targets - over,non targets epa - over
2557958,46,2.792,30,1.738,16,1.054
2555383,53,2.358,48,2.130,5,0.228
79848,83,3.432,66,2.770,17,0.662
2534832,1,0.037,1,0.037,0,0.000
2556363,9,0.269,6,0.103,3,0.166

### Man Analysis

In [20]:
df = pd.merge(player_season_coverages[['displayName','snaps','position','man-total','zone-total']],
              man_production_reduction.drop(columns=['name']),
              left_index=True,right_index=True)

In [21]:
df = pd.merge(df,zone_production_reduction.drop(columns=['name']),
              left_index=True,right_index=True)

In [22]:
df = pd.merge(df,defensive_target_coverage_epa,
              left_index=True,right_index=True)

In [23]:
df = pd.merge(df,man_non_targeted_epa_analysis,
              left_index=True,right_index=True)

In [24]:
df

,displayName,snaps,position,man-total,zone-total,man targeted coverage count,total man delta epa,mean man delta epa,zone targeted coverage count,total zone delta epa,...,zone-over targets,zone-over targets epa,man-over targets,man-over targets epa,non targets,non targets epa,non targets - iso,non targets epa - iso,non targets - over,non targets epa - over
306,Dominique Rodgers-Cromartie,64,CB,15,49,2,0.442579,0.221290,5,-5.355782,...,3.0,0.573568,2.0,1.185579,13,0.896,3,0.106,10,0.790
1302,Aqib Talib,202,CB,44,158,10,-1.184709,-0.118471,10,-5.577872,...,6.0,4.573684,3.0,1.731820,33,1.225,18,0.792,15,0.433
2307,Orlando Scandrick,462,CB,246,216,60,8.473536,0.141226,23,-5.752900,...,12.0,1.049774,22.0,10.951907,180,5.947,106,3.285,74,2.662
4365,Brandon Carr,517,CB,248,258,54,-3.716949,-0.068832,20,-5.128446,...,11.0,-7.938035,20.0,-2.395061,181,8.373,112,4.093,69,4.280
71251,Patrick Chung,525,SS,168,313,35,1.050480,0.030014,35,-11.977567,...,23.0,-7.777324,18.0,-6.030866,128,3.448,80,2.172,48,1.276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2561316,Jalen Davis,23,CB,12,10,5,6.300327,1.260065,2,-1.117703,...,2.0,-1.028703,2.0,2.550343,7,0.139,5,0.000,2,0.139
2561318,Tae Davis,190,ILB,5,151,2,2.831041,1.415520,7,-4.121987,...,7.0,4.320193,NaN,NaN,3,0.000,3,0.000,0,0.000
2561340,Tre Herndon,38,CB,25,12,5,1.205910,0.241182,2,0.305361,...,NaN,NaN,2.0,1.336160,19,0.386,14,0.263,5,0.123
2561417,Charvarius Ward,67,CB,34,33,10,0.674194,0.067419,2,3.988404,...,NaN,NaN,1.0,-0.209244,22,1.406,19,1.406,3,0.000
2561527,Mike Ford,198,CB,83,115,15,11.249367,0.749958,12,10.071364,...,5.0,10.937410,5.0,5.530242,66,3.058,42,1.284,24,1.774

In [25]:
snap_threshold = 200

In [26]:
df = df[df['snaps'] > snap_threshold]
df

,displayName,snaps,position,man-total,zone-total,man targeted coverage count,total man delta epa,mean man delta epa,zone targeted coverage count,total zone delta epa,...,zone-over targets,zone-over targets epa,man-over targets,man-over targets epa,non targets,non targets epa,non targets - iso,non targets epa - iso,non targets - over,non targets epa - over
1302,Aqib Talib,202,CB,44,158,10,-1.184709,-0.118471,10,-5.577872,...,6.0,4.573684,3.0,1.731820,33,1.225,18,0.792,15,0.433
2307,Orlando Scandrick,462,CB,246,216,60,8.473536,0.141226,23,-5.752900,...,12.0,1.049774,22.0,10.951907,180,5.947,106,3.285,74,2.662
4365,Brandon Carr,517,CB,248,258,54,-3.716949,-0.068832,20,-5.128446,...,11.0,-7.938035,20.0,-2.395061,181,8.373,112,4.093,69,4.280
71251,Patrick Chung,525,SS,168,313,35,1.050480,0.030014,35,-11.977567,...,23.0,-7.777324,18.0,-6.030866,128,3.448,80,2.172,48,1.276
71423,Brian Orakpo,303,OLB,3,96,1,-0.343774,-0.343774,2,-2.589056,...,2.0,-2.204056,1.0,-0.136774,2,0.033,2,0.033,0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2560966,Jerome Baker,343,LB,34,270,3,1.639706,0.546569,13,-1.285941,...,13.0,-3.346637,2.0,3.529112,31,0.728,9,0.224,22,0.504
2561001,Grant Haley,245,CB,124,110,25,11.187032,0.447481,12,-1.041468,...,5.0,1.822019,15.0,8.078860,95,4.345,40,1.607,55,2.738
2561015,Lorenzo Carter,277,OLB,12,73,2,-2.469402,-1.234701,2,-1.358969,...,1.0,0.729972,1.0,-1.011689,10,0.320,6,0.073,4,0.247
2561039,Carlton Davis,362,CB,219,143,43,-7.638645,-0.177643,13,7.892960,...,5.0,0.161711,14.0,0.250348,169,5.541,122,3.842,47,1.699
2561132,Foye Oluokun,262,LB,35,210,2,1.453587,0.726794,8,1.255500,...,5.0,1.784756,1.0,0.273045,32,0.913,8,0.137,24,0.776

In [27]:
df.keys()

Index(['displayName', 'snaps', 'position', 'man-total', 'zone-total',
       'man targeted coverage count', 'total man delta epa',
       'mean man delta epa', 'zone targeted coverage count',
       'total zone delta epa', 'mean zone delta epa', 'targets',
       'zone targets', 'zone targets epa', 'man targets', 'man targets epa',
       'zone-over targets', 'zone-over targets epa', 'man-over targets',
       'man-over targets epa', 'non targets', 'non targets epa',
       'non targets - iso', 'non targets epa - iso', 'non targets - over',
       'non targets epa - over'],
      dtype='object')

In [28]:
df['target %'] = ((df['targets'] / df['snaps']) * 100).round(1)
df['man target %'] = ((df['man targeted coverage count'] / df['man-total']) * 100).round(1)
df['zone target %'] = ((df['zone targeted coverage count'] / df['zone-total']) * 100).round(1)
df['total delta epa'] = df['total man delta epa'] + df['total zone delta epa']
df['mean total delta epa'] = df['total delta epa'] / df['targets']

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [29]:
cb_df = df[df['position'] == 'CB']

In [30]:
cb_df.sort_values('target %')

,displayName,snaps,position,man-total,zone-total,man targeted coverage count,total man delta epa,mean man delta epa,zone targeted coverage count,total zone delta epa,...,non targets epa,non targets - iso,non targets epa - iso,non targets - over,non targets epa - over,target %,man target %,zone target %,total delta epa,mean total delta epa
2552389,Damarious Randall,587,CB,46,531,9,1.033898,0.114878,8,0.806912,...,2.892,31,2.426,6,0.466,3.4,19.6,1.5,1.840810,0.092041
2560795,Avonte Maddox,343,CB,60,281,8,2.303399,0.287925,15,-3.003652,...,2.426,40,1.756,9,0.670,7.9,13.3,5.3,-0.700253,-0.025935
2506789,Tramon Williams,540,CB,103,425,19,-6.962754,-0.366461,16,-5.592412,...,3.748,48,1.761,34,1.987,8.0,18.4,3.8,-12.555166,-0.291981
2495507,Richard Sherman,421,CB,208,213,24,-1.208669,-0.050361,14,12.430706,...,9.786,132,7.535,39,2.251,9.7,11.5,6.6,11.222037,0.273708
2553353,Darryl Roberts,403,CB,62,341,12,-5.440164,-0.453347,23,2.020391,...,1.429,31,1.129,19,0.300,9.9,19.4,6.7,-3.419773,-0.085494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2558065,Adoree' Jackson,497,CB,142,349,47,-3.098415,-0.065924,45,-6.041682,...,6.210,60,3.885,33,2.325,20.7,33.1,12.9,-9.140097,-0.088739
2540155,Xavier Rhodes,342,CB,204,137,52,-3.637398,-0.069950,15,-1.270702,...,9.104,82,5.474,60,3.630,20.8,25.5,10.9,-4.908100,-0.069128
2560952,Jaire Alexander,403,CB,170,225,49,-1.467478,-0.029949,25,-3.215345,...,6.185,78,4.585,37,1.600,21.1,28.8,11.1,-4.682823,-0.055092
2558157,Ahkello Witherspoon,337,CB,173,163,52,3.265139,0.062791,15,-0.801552,...,6.773,90,5.539,24,1.234,21.4,30.1,9.2,2.463587,0.034216
2555277,Eli Apple,351,CB,174,177,66,0.272638,0.004131,31,-0.446696,...,8.376,123,4.447,57,3.929,30.5,37.9,17.5,-0.174058,-0.001627

In [31]:
cb_df.keys()

Index(['displayName', 'snaps', 'position', 'man-total', 'zone-total',
       'man targeted coverage count', 'total man delta epa',
       'mean man delta epa', 'zone targeted coverage count',
       'total zone delta epa', 'mean zone delta epa', 'targets',
       'zone targets', 'zone targets epa', 'man targets', 'man targets epa',
       'zone-over targets', 'zone-over targets epa', 'man-over targets',
       'man-over targets epa', 'non targets', 'non targets epa',
       'non targets - iso', 'non targets epa - iso', 'non targets - over',
       'non targets epa - over', 'target %', 'man target %', 'zone target %',
       'total delta epa', 'mean total delta epa'],
      dtype='object')

In [32]:
cb_performance = cb_df[['displayName','position','snaps','man-total','zone-total',
                        'targets','man targeted coverage count','zone targeted coverage count',
                        'target %','man target %','zone target %',
                        'total delta epa','total man delta epa','total zone delta epa',
                        'mean total delta epa','mean man delta epa','mean zone delta epa']]

In [57]:
man_cb_performance = cb_df[['displayName','position','snaps','man-total','man targeted coverage count',
                            'man target %','non targets', 'non targets epa','non targets - iso',
                            'non targets epa - iso', 'non targets - over','non targets epa - over']]

In [45]:
def score(df, key, score_name):
    mu = df[key].mean()
    s = df[key].std()
    
    df[score_name] = ((-(df[key] - mu) / s) * 10 + 50).round(1)

In [46]:
score(cb_performance, 'mean total delta epa', 'Total Score')
score(cb_performance, 'mean man delta epa', 'Man Score')
score(cb_performance, 'mean zone delta epa', 'Zone Score')

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [51]:
score(cb_performance, 'target %', 'Target % Score')
score(cb_performance, 'man target %', 'Man Target % Score')
score(cb_performance, 'zone target %', 'Zone Target % Score')

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [52]:
sort_key = 'total delta epa'
cb_performance.sort_values(sort_key).head(10)

,displayName,position,snaps,man-total,zone-total,targets,man targeted coverage count,zone targeted coverage count,target %,man target %,...,total zone delta epa,mean total delta epa,mean man delta epa,mean zone delta epa,Total Score,Man Score,Zone Score,Target % Score,Man Target % Score,Zone Target % Score
2543681,Kyle Fuller,CB,593,246,346,99,56,31,16.7,22.8,...,-27.847193,-0.449328,-0.297076,-0.898297,66.7,58.7,67.7,45.2,45.2,50.0
2555175,James Bradberry,CB,538,136,401,102,36,53,19.0,26.5,...,-27.406165,-0.395830,-0.360237,-0.517097,64.5,60.8,59.9,38.5,37.1,33.5
2558067,Marlon Humphrey,CB,437,239,197,64,45,17,14.6,18.8,...,-14.716760,-0.576218,-0.492471,-0.865692,71.8,65.2,67.1,51.4,54.0,51.5
2557927,Desmond King,CB,432,122,298,53,23,29,12.3,18.9,...,-30.241365,-0.678675,-0.249062,-1.042806,76.0,57.1,70.7,58.2,53.8,47.2
2533062,Stephon Gilmore,CB,588,356,231,97,66,22,16.5,18.5,...,-5.455122,-0.328620,-0.400319,-0.247960,61.8,62.1,54.4,45.8,54.7,48.0
2495872,Johnathan Joseph,CB,445,71,374,66,18,43,14.8,25.4,...,-24.369903,-0.456898,-0.321408,-0.566742,67.0,59.5,60.9,50.8,39.5,40.2
2555280,Jalen Ramsey,CB,508,223,284,91,58,27,17.9,26.0,...,-13.027533,-0.277932,-0.211452,-0.482501,59.7,55.9,59.2,41.7,38.2,48.0
2543811,Pierre Desir,CB,485,234,251,58,35,17,12.0,15.0,...,-18.087348,-0.427201,-0.191152,-1.063962,65.8,55.2,71.1,59.1,62.3,58.6
2555539,Xavien Howard,CB,404,155,249,56,34,13,13.9,21.9,...,-7.774421,-0.433864,-0.485940,-0.598032,66.0,65.0,61.6,53.5,47.2,64.8
2557867,Tre'Davious White,CB,487,253,233,64,46,10,13.1,18.2,...,-7.930646,-0.371639,-0.344658,-0.793065,63.5,60.3,65.6,55.9,55.3,68.4

In [53]:
sort_key = 'mean total delta epa'
cb_performance.sort_values(sort_key).head(10)

,displayName,position,snaps,man-total,zone-total,targets,man targeted coverage count,zone targeted coverage count,target %,man target %,...,total zone delta epa,mean total delta epa,mean man delta epa,mean zone delta epa,Total Score,Man Score,Zone Score,Target % Score,Man Target % Score,Zone Target % Score
2557927,Desmond King,CB,432,122,298,53,23,29,12.3,18.9,...,-30.241365,-0.678675,-0.249062,-1.042806,76.0,57.1,70.7,58.2,53.8,47.2
2558067,Marlon Humphrey,CB,437,239,197,64,45,17,14.6,18.8,...,-14.716760,-0.576218,-0.492471,-0.865692,71.8,65.2,67.1,51.4,54.0,51.5
2555552,Ryan Smith,CB,247,83,164,36,19,15,14.6,22.9,...,-18.069314,-0.492224,0.018382,-1.204621,68.4,48.2,74.0,51.4,45.0,49.6
2555177,Mackensie Alexander,CB,295,115,172,51,27,18,17.3,23.5,...,-9.777895,-0.457144,-0.501350,-0.543216,67.0,65.5,60.5,43.5,43.7,44.1
2495872,Johnathan Joseph,CB,445,71,374,66,18,43,14.8,25.4,...,-24.369903,-0.456898,-0.321408,-0.566742,67.0,59.5,60.9,50.8,39.5,40.2
2543681,Kyle Fuller,CB,593,246,346,99,56,31,16.7,22.8,...,-27.847193,-0.449328,-0.297076,-0.898297,66.7,58.7,67.7,45.2,45.2,50.0
2555539,Xavien Howard,CB,404,155,249,56,34,13,13.9,21.9,...,-7.774421,-0.433864,-0.485940,-0.598032,66.0,65.0,61.6,53.5,47.2,64.8
2543811,Pierre Desir,CB,485,234,251,58,35,17,12.0,15.0,...,-18.087348,-0.427201,-0.191152,-1.063962,65.8,55.2,71.1,59.1,62.3,58.6
2555175,James Bradberry,CB,538,136,401,102,36,53,19.0,26.5,...,-27.406165,-0.395830,-0.360237,-0.517097,64.5,60.8,59.9,38.5,37.1,33.5
2557867,Tre'Davious White,CB,487,253,233,64,46,10,13.1,18.2,...,-7.930646,-0.371639,-0.344658,-0.793065,63.5,60.3,65.6,55.9,55.3,68.4

In [54]:
sort_key = 'mean man delta epa'
cb_performance.sort_values(sort_key).head(10)

,displayName,position,snaps,man-total,zone-total,targets,man targeted coverage count,zone targeted coverage count,target %,man target %,...,total zone delta epa,mean total delta epa,mean man delta epa,mean zone delta epa,Total Score,Man Score,Zone Score,Target % Score,Man Target % Score,Zone Target % Score
2556559,Mike Hilton,CB,375,119,219,58,23,29,15.5,19.3,...,10.109893,-0.083302,-0.649627,0.348617,51.8,70.4,42.2,48.8,52.9,33.5
2539237,D.J. Hayden,CB,257,93,150,32,22,9,12.5,23.7,...,0.732036,-0.357969,-0.553956,0.081337,63.0,67.3,47.7,57.6,43.2,61.7
2555177,Mackensie Alexander,CB,295,115,172,51,27,18,17.3,23.5,...,-9.777895,-0.457144,-0.501350,-0.543216,67.0,65.5,60.5,43.5,43.7,44.1
2558067,Marlon Humphrey,CB,437,239,197,64,45,17,14.6,18.8,...,-14.716760,-0.576218,-0.492471,-0.865692,71.8,65.2,67.1,51.4,54.0,51.5
2555539,Xavien Howard,CB,404,155,249,56,34,13,13.9,21.9,...,-7.774421,-0.433864,-0.485940,-0.598032,66.0,65.0,61.6,53.5,47.2,64.8
2553353,Darryl Roberts,CB,403,62,341,40,12,23,9.9,19.4,...,2.020391,-0.085494,-0.453347,0.087843,51.9,63.9,47.5,65.3,52.7,59.0
2553500,Bryce Callahan,CB,415,191,213,48,27,20,11.6,14.1,...,-2.861385,-0.314407,-0.452968,-0.143069,61.2,63.9,52.3,60.3,64.3,48.4
2540197,Nickell Robey-Coleman,CB,340,83,255,47,16,22,13.8,19.3,...,-8.113978,-0.323850,-0.444185,-0.368817,61.6,63.6,56.9,53.8,52.9,51.5
2559164,Michael Davis,CB,336,172,164,60,41,8,17.9,23.8,...,5.840343,-0.205071,-0.442551,0.730043,56.8,63.5,34.4,41.7,43.0,66.0
80668,Captain Munnerlyn,CB,397,129,247,63,28,29,15.9,21.7,...,1.258052,-0.171950,-0.431818,0.043381,55.4,63.2,48.5,47.6,47.6,39.4

In [55]:
sort_key = 'mean zone delta epa'
cb_performance.sort_values(sort_key).head(10)

,displayName,position,snaps,man-total,zone-total,targets,man targeted coverage count,zone targeted coverage count,target %,man target %,...,total zone delta epa,mean total delta epa,mean man delta epa,mean zone delta epa,Total Score,Man Score,Zone Score,Target % Score,Man Target % Score,Zone Target % Score
2555552,Ryan Smith,CB,247,83,164,36,19,15,14.6,22.9,...,-18.069314,-0.492224,0.018382,-1.204621,68.4,48.2,74.0,51.4,45.0,49.6
2543811,Pierre Desir,CB,485,234,251,58,35,17,12.0,15.0,...,-18.087348,-0.427201,-0.191152,-1.063962,65.8,55.2,71.1,59.1,62.3,58.6
2557927,Desmond King,CB,432,122,298,53,23,29,12.3,18.9,...,-30.241365,-0.678675,-0.249062,-1.042806,76.0,57.1,70.7,58.2,53.8,47.2
2543681,Kyle Fuller,CB,593,246,346,99,56,31,16.7,22.8,...,-27.847193,-0.449328,-0.297076,-0.898297,66.7,58.7,67.7,45.2,45.2,50.0
2543855,Bene' Benwikere,CB,250,95,150,44,29,13,17.6,30.5,...,-11.498143,-0.316553,-0.083800,-0.884473,61.3,51.6,67.5,42.6,28.3,51.2
2558067,Marlon Humphrey,CB,437,239,197,64,45,17,14.6,18.8,...,-14.716760,-0.576218,-0.492471,-0.865692,71.8,65.2,67.1,51.4,54.0,51.5
2557867,Tre'Davious White,CB,487,253,233,64,46,10,13.1,18.2,...,-7.930646,-0.371639,-0.344658,-0.793065,63.5,60.3,65.6,55.9,55.3,68.4
2555531,Anthony Brown,CB,397,146,240,53,26,22,13.4,17.8,...,-14.192913,-0.250170,0.035919,-0.645132,58.6,47.6,62.6,55.0,56.2,49.2
2552265,Steven Nelson,CB,603,365,238,101,79,17,16.7,21.6,...,-10.572826,-0.149603,-0.057432,-0.621931,54.5,50.7,62.1,45.2,47.8,57.4
2555539,Xavien Howard,CB,404,155,249,56,34,13,13.9,21.9,...,-7.774421,-0.433864,-0.485940,-0.598032,66.0,65.0,61.6,53.5,47.2,64.8

In [56]:
sort_key = 'target %'
cb_performance.sort_values(sort_key).head(10)

,displayName,position,snaps,man-total,zone-total,targets,man targeted coverage count,zone targeted coverage count,target %,man target %,...,total zone delta epa,mean total delta epa,mean man delta epa,mean zone delta epa,Total Score,Man Score,Zone Score,Target % Score,Man Target % Score,Zone Target % Score
2552389,Damarious Randall,CB,587,46,531,20,9,8,3.4,19.6,...,0.806912,0.092041,0.114878,0.100864,44.7,45.0,47.3,84.5,52.2,79.3
2560795,Avonte Maddox,CB,343,60,281,27,8,15,7.9,13.3,...,-3.003652,-0.025935,0.287925,-0.200243,49.5,39.2,53.4,71.2,66.1,64.5
2506789,Tramon Williams,CB,540,103,425,43,19,16,8.0,18.4,...,-5.592412,-0.291981,-0.366461,-0.349526,60.3,61.0,56.5,70.9,54.9,70.3
2495507,Richard Sherman,CB,421,208,213,41,24,14,9.7,11.5,...,12.430706,0.273708,-0.050361,0.887908,37.3,50.5,31.2,65.9,70.0,59.4
2553353,Darryl Roberts,CB,403,62,341,40,12,23,9.9,19.4,...,2.020391,-0.085494,-0.453347,0.087843,51.9,63.9,47.5,65.3,52.7,59.0
2556934,Javien Elliott,CB,209,65,131,21,13,5,10.0,20.0,...,-0.444710,0.210643,0.374478,-0.088942,39.9,36.3,51.2,65.0,51.4,70.3
2558108,Nate Hairston,CB,210,91,117,21,8,10,10.0,8.8,...,5.957007,0.677029,1.032575,0.595701,20.9,14.4,37.1,65.0,76.0,51.9
2495504,Patrick Peterson,CB,505,166,336,51,19,20,10.1,11.4,...,-5.092603,0.152921,0.678504,-0.254630,42.2,26.2,54.6,64.7,70.2,61.7
2557961,Quincy Wilson,CB,259,106,152,29,18,9,11.2,17.0,...,-0.307241,-0.242775,-0.374068,-0.034138,58.3,61.3,50.0,61.5,57.9,62.1
2552488,Marcus Peters,CB,477,131,345,54,29,23,11.3,22.1,...,-5.867907,-0.016377,0.171846,-0.255126,49.1,43.1,54.6,61.2,46.8,59.0