In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import os
import glob

In [2]:
basepath = os.path.expanduser('~/Documents/programming-projects/nfl-big-data/calculated-data')

In [3]:
glob.glob(os.path.join(basepath,'*.csv'))

['/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/man play results.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/player max speed + accel.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/man coverage production reduction.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/offensive production.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/player season coverages.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/team target coverage epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/team personal epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/non targeted man coverage epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/coverage scheme epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/targeted defensive player epa analysis.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/zone coverage production reduction.csv',
 '/Users/jacobhow/Documents/programming-projects/nfl-big-data/calculated-data/zone play results.csv']

## Team Level

In [4]:
team_personal_epa = pd.read_csv(os.path.join(basepath,'team personal epa analysis.csv'))

In [5]:
team_scheme_epa = pd.read_csv(os.path.join(basepath,'coverage scheme epa analysis.csv'))

In [6]:
target_coverage_epa = pd.read_csv(os.path.join(basepath,'team target coverage epa analysis.csv'))

In [7]:
team_scheme_epa.head()

,team,play count,cover 0 count,cover 1 count,cover 2 count,cover 3 count,cover 4 count,cover 6 count,cover 0 percent,cover 1 percent,...,cover 3 epa,cover 4 epa,cover 6 epa,overall epa rate,cover 0 epa rate,cover 1 epa rate,cover 2 epa rate,cover 3 epa rate,cover 4 epa rate,cover 6 epa rate
0,CHI,621,25,203,147,61,95,90,4.0,32.7,...,-4.563688,-42.775964,2.178439,-0.039385,0.102864,0.238308,-0.170072,-0.037716,-0.353520,0.018004
1,BUF,507,36,191,101,49,77,53,7.1,37.7,...,0.692472,-3.749987,-10.104115,-0.000929,-0.019888,-0.078861,0.203632,0.005723,-0.030992,-0.083505
2,BAL,596,78,236,94,67,60,57,13.1,39.6,...,-4.107474,14.625985,-15.831695,0.017707,0.077028,-0.146907,0.211167,-0.033946,0.120876,-0.130840
3,MIN,456,23,144,86,49,99,55,5.0,31.6,...,-4.847184,-15.370724,23.046011,0.040269,-0.051042,0.218759,-0.039331,-0.040059,-0.127031,0.190463
4,NE,613,93,305,96,37,55,27,15.2,49.8,...,4.465144,19.412516,5.699166,0.032357,-0.046609,-0.229732,0.195827,0.036902,0.160434,0.047101

In [8]:
team_personal_epa.head()

,team,play count,heavy count,standard count,nickel count,dime count,quarter count,heavy percent,standard percent,nickel percent,...,standard epa,nickel epa,dime epa,quarter epa,overall epa rate,heavy epa rate,standard epa rate,nickel epa rate,dime epa rate,quarter epa rate
0,CHI,621,3,78,496,42,2,0.5,12.6,79.9,...,7.599955,-25.658569,-11.040015,0.931636,-0.039385,0.030652,0.062810,-0.212054,-0.091240,0.007699
1,BUF,507,0,65,440,0,0,0.0,12.8,86.8,...,-5.723763,5.249235,0.000000,0.000000,-0.000929,0.000000,-0.047304,0.043382,0.000000,0.000000
2,BAL,596,1,56,308,226,5,0.2,9.4,51.7,...,15.185915,8.890013,-10.222289,-4.861716,0.017707,0.012903,0.125503,0.073471,-0.084482,-0.040179
3,MIN,456,2,49,398,6,0,0.4,10.7,87.3,...,10.348018,10.744882,1.064906,0.000000,0.040269,-0.031420,0.085521,0.088801,0.008801,0.000000
4,NE,613,10,51,297,182,73,1.6,8.3,48.5,...,19.217143,28.082868,-22.970695,-10.730886,0.032357,0.051540,0.158819,0.232090,-0.189840,-0.088685

In [9]:
target_coverage_epa.head()

,team,play count,man count,zone count,man+zone count,checkdown count,no coverage count,man percent,zone percent,man+zone percent,...,zone epa,man+zone epa,checkdown epa,no coverage epa,overall epa rate,man epa rate,zone epa rate,man+zone epa rate,checkdown epa rate,no coverage epa rate
0,CHI,595,153,201,26,65,150,25.7,33.8,4.4,...,-10.418636,-3.281712,-14.807724,-2.621828,-0.010730,0.161737,-0.051834,-0.126220,-0.227811,-0.017479
1,BUF,486,108,155,23,77,123,22.2,31.9,4.7,...,-0.124513,15.822149,-6.914055,9.499362,0.019237,-0.082722,-0.000803,0.687920,-0.089793,0.077231
2,MIN,436,122,149,17,84,64,28.0,34.2,3.9,...,9.484143,-1.280299,2.744966,10.321282,0.074216,0.090887,0.063652,-0.075312,0.032678,0.161270
3,NE,589,163,177,45,69,135,27.7,30.1,7.6,...,35.574739,-15.227899,-9.772139,38.720231,0.056979,-0.096530,0.200987,-0.338398,-0.141625,0.286817
4,BAL,539,156,164,23,82,114,28.9,30.4,4.3,...,18.049344,10.472397,-6.140205,26.131998,0.062272,-0.095827,0.110057,0.455322,-0.074881,0.229228